---

kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
  - name: go-mod
    image: golang:1.13-alpine3.10-arm
    commands:
      - go mod vendor
    environment:
      GO111MODULE: "on"

  - name: static-check
    image: golangci/golangci-lint:armv7
    commands:
      - golangci-lint run --deadline 2m -v ./...
    environment:
      CGO_ENABLED: 0
      GO111MODULE: "on"

  - name: test
    image: golang:1.13-alpine3.10-arm
    commands:
      - go test -mod=vendor -v ./...
    environment:
      CGO_ENABLED: 0
      GO111MODULE: "on"

  - name: build-go
    image: golang:1.13-alpine3.10-arm
    commands:
      - go build -mod=vendor -v

  - name: build-docker
    image: quantonganh/docker:19.03.3-rc1-armv7
    commands:
      - docker build -t quantonganh/blog:${DRONE_SOURCE_BRANCH} .
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: deploy
    image: quantonganh/drone-ssh:arm
    settings:
      host: quanta.dynu.net
      username: root
      key:
        from_secret: ssh_key
      port: 22022
      script:
        - cd /data
        - docker-compose stop blog
        - docker-compose up -d blog
    when:
      branch:
        - master

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
