---

kind: pipeline
name: default

steps:
  - name: go-mod
    image: golang:1.13-alpine3.10-arm
    commands:
      - go mod vendor
    environment:
      GO111MODULE: "on"

  - name: static-check
    image: golangci/golangci-lint:v1.17.1
    commands:
      - golangci-lint run -v ./...
    environment:
      GO111MODULE: "on"

  - name: test
    image: golang:1.13-alpine3.10-arm
    commands:
      - go test -mod=vendor -v ./...
    environment:
      CGO_ENABLED: 0
      GO111MODULE: "on"

  - name: build
    image: golang:1.13-alpine3.10-arm
    commands:
      - go build -mod=vendor -o blog -v
