---

kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
  - name: go-mod
    image: golang:1.15@sha256:4e8d5b8651f6ad69d9d15cf14ae8cfbc94fa33269f521e42598a2c7dbe2cfedd
    privileged: true
    commands:
      - env
      - go mod vendor
    environment:
      GO111MODULE: "on"

  - name: static-check
    image: golangci/golangci-lint:v1.33-alpine@sha256:0b26f3287b14b4f254b26f42cd250f25f4bdc69c1a4fc0db53093976372f70b2
    privileged: true
    commands:
      - if git --no-pager diff --name-only ${DRONE_COMMIT_LINK##*/} | grep -q "\.go$"; then golangci-lint run --deadline 2m -v ./...; fi
    environment:
      CGO_ENABLED: 0
      GO111MODULE: "on"

  - name: test
    image: golang:1.15@sha256:4e8d5b8651f6ad69d9d15cf14ae8cfbc94fa33269f521e42598a2c7dbe2cfedd
    privileged: true
    commands:
      - if git --no-pager diff --name-only ${DRONE_COMMIT_LINK##*/} | grep -q "\.go$"; then go test -mod=vendor -v ./...; fi
    environment:
      CGO_ENABLED: 0
      GO111MODULE: "on"

  - name: build-go
    image: golang:1.15@sha256:4e8d5b8651f6ad69d9d15cf14ae8cfbc94fa33269f521e42598a2c7dbe2cfedd
    privileged: true
    commands:
      - go build -mod=vendor -v

  - name: build-docker
    image: quantonganh/docker:19.03.3-rc1-armv7
    commands:
      - docker build -t quantonganh/blog:${DRONE_SOURCE_BRANCH} .
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: deploy
    image: quantonganh/drone-ssh:arm
    settings:
      host: quanta.dynu.net
      username: root
      key:
        from_secret: ssh_key
      port: 22022
      script:
        - cd /data
        - docker-compose stop blog
        - docker-compose up -d blog
    when:
      branch:
        - master

  - name: check
    image: quantonganh/curl:armv7-alpine
    commands:
      - curl -s -w "%{http_code}" -I quanta.dynu.net -o /dev/null | grep -q 307

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
