// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	post "github.com/quantonganh/blog/post"
	mock "github.com/stretchr/testify/mock"
)

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

// SendConfirmationEmail provides a mock function with given fields: to, token
func (_m *Mailer) SendConfirmationEmail(to string, token string) error {
	ret := _m.Called(to, token)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(to, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendNewsletter provides a mock function with given fields: posts
func (_m *Mailer) SendNewsletter(posts []*post.Post) {
	_m.Called(posts)
}

// SendThankYouEmail provides a mock function with given fields: to
func (_m *Mailer) SendThankYouEmail(to string) error {
	ret := _m.Called(to)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
